modLoader="javafml" #mandatory

loaderVersion="[51,)" 

license="All rights reserved"

[[mods]] #mandatory
modId="monsterplus" #mandatory

version="1.1.8.2" #mandatory

displayName="Monster Plus" #mandatory

logoFile="logo.png" #optional

authors="Nitespring"


# The description text for the mod (multi line!) (#mandatory)
description='''New challenges await you, go explore'''


# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.monsterplus]] #optional
    modId="forge" #mandatory
    mandatory=true 
    versionRange="${forge_version_range}" 
    # An ordering relationship for the dependency - BEFORE or AFTER required if the dependency is not mandatory
    # BEFORE - This mod is loaded BEFORE the dependency
    # AFTER - This mod is loaded AFTER the dependency
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT, or SERVER
    side="BOTH"
[[dependencies.monsterplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,)"
    ordering="NONE"
    side="BOTH"
